general.import = [ "~/.dots/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
bold = { family = "DejaVuSansM Nerd Font Mono", style = "Bold" }
italic = { family = "DejaVuSansM Nerd Font Mono", style = "Oblique" }
size = 13

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9
padding.x = 10
padding.y = 3

[keyboard]
bindings = [
    { key = "K", mods = "Control", action = "ScrollLineUp" },
    { key = "J", mods = "Control", action = "ScrollLineDown" },
    { key = "F11", action = "ToggleFullscreen" },
    { key = "Space", mods = "Alt", action = "ToggleViMode" }
]
