# Cursor size
env = XCURSOR_SIZE,18
env = HYPRCURSOR_SIZE,18

# Force all apps to use Wayland
env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = GDK_SCALE,1
env = DOCKER_HOST,unix:///run/user/$(id -u)/podman/podman.sock

xwayland {
  force_zero_scaling = true
}

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Don't show update on first launch
ecosystem {
  no_update_news = true
}
