# --------------------------------------------------------
#          DEDICATED MEDIA WORKSPACE CONFIG
# --------------------------------------------------------

$mainMod = MOD4

# 1. WORKSPACE DEFINITION & AUTO-LAUNCH (on-created-empty)
workspace = name:youtube, on-created-empty:ghostty -e youtube-tui
workspace = name:music, on-created-empty:ghostty -e youtube-tui

windowrule {
    name = youtube
    workspace = youtube
    match:title = ^(youtube-tui|mpv)$ 
    fullscreen = true
}
windowrule {
    name = music
    workspace = music
    match:title = ^(youtube-tui|mpv)$ 
    fullscreen = true
}

# --- Keybinds for Custom Media Workspaces (Enter Submap) ---
# Mod+Y: Switch to 'youtube' workspace AND enter 'stack_nav' mode
bind = $mainMod, Y, workspace, name:youtube

# Mod+M: Switch to 'music' workspace AND enter 'stack_nav' mode
bind = $mainMod, M, workspace, name:music
