windowrule {
    name = global
    match:class = .*
    suppress_event = maximize
}

# --- Floating & Centering ---
windowrule {
    name = float-script
    match:class = ^(.*FloatingWindow)$
    float = on
    center = on 
    size = 75% 75%
}

windowrule {
    name = float-picker
    match:class = xdg-desktop-portal-gtk 
    match:title = ^(Open.*Files?|Save.*Files?|All Files|Save)
    float = on
    center = on 
    size = 1200 800
}

windowrule {
    name = float-rust
    match:title = ^(System Monitor|Monitor Manager)$ 
    float = on
    center = on 
    size = 519 439
}

# --- Opacity Rules ---
windowrule {
    name = medium-transperent
    match:class = .*
    opacity = 0.95 0.92
}

windowrule {
    name = no-transparent
    match:class = ^(zoom|vlc|mpv|imv|jetbrains-phpstorm)$
    opacity = 1.0 1.0
}

windowrule {
    name = semi-transperent
    match:class = ^(firefox|google-chrome-stable|google-chrome)$
    opacity = 0.97 0.94
}

# --- Screen Sharing Fix ---
# Moves the "is sharing your screen" indicator way off-screen
windowrule {
    name = hide-programs
    match:initial_title = ^(.*is sharing your screen.*)$
    move = 0 -1000000
}
