# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.*

# Float and center settings and previews
windowrule = float, class:^(Wiremix|BTop|Impala|BlueTUI)$
windowrule = size 800 600, class:^(Wiremix|BTop|Impala|BlueTUI)$
windowrule = center, class:^(Wiremix|BTop|Impala|BlueTUI)$

# Center any floating window
windowrulev2 = center, floating:1, initialClass:^(Google-chrome|google-chrome)$
windowrulev2 = size 90% 90%, floating:1, initialClass:^(Google-chrome|google-chrome)$
windowrulev2 = tile, class:^(Google-chrome|google-chrome-stable)$

windowrulev2 = float, initialClass:^(FloatingScript)$
windowrulev2 = center, initialClass:^(FloatingScript)$
windowrulev2 = size 50% 50%, initialClass:^(FloatingScript)$
# Float and center file pickers
windowrule = float, class:xdg-d../..sktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)

# Just dash of opacity
windowrule = opacity 0.97 0.9, class:.*
windowrule = opacity 1 0.97, class:^(google-chrome-stable)$
windowrule = opacity 1 1, initialTitle:^(youtube.com_/)$ # Youtube
windowrule = opacity 1 1, class:^(zoom|vlc|mpv|imv)$

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Proper background blur for wofi
layerrule = blur,wofi
