# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.*

windowrulev2 = float, initialClass:^(FloatingWindow)$
windowrulev2 = center, initialClass:^(FloatingWindow)$
windowrulev2 = size 75% 75%, initialClass:^(FloatingWindow)$
# Float and center file pickers
windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = size 1200 800, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)

# Just dash of opacity
windowrule = opacity 0.95 0.92, class:.*
windowrule = opacity 0.98 0.93, class:^(firefox)$
windowrule = opacity 1 1, class:^(zoom|vlc|mpv|imv)$

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Proper background blur for wofi
layerrule = blur,fuzzel

windowrulev2 = move 0 -1000000, initialTitle:^(.*is sharing your screen.*)$

# Scroll faster in the terminal
windowrule = scrolltouchpad 1.5, class:Alacritty
