##### General Settings #####
set -g history-limit 25000
set -g mouse off
set -sg escape-time 10
setw -g mode-keys vi
set -g default-terminal "screen-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g prefix C-s

##### Status Bar #####
set -g status on
set -g status-position top
#set -g status-justify centre
set -g status-style fg=#c6d0f5,bg=default
set -g status-left ""
set -g status-left-style fg=#c6d0f5
set -g status-right "%H:%M"
set -g status-right-style fg=#c6d0f5
set -g window-status-style fg=#a6adc8,bg=default
set -g window-status-current-style fg=#b4befe,bg=default,bold

##### Key Bindings #####
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
bind v split-window -h -c "#{pane_current_path}"
bind a split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

##### TPM #####
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'

