# Catppuccin Latte — Hyprlock

$color = rgba(239,241,245,1.0)
$inner_color = rgba(239,241,245,0.9)
$outer_color = rgba(76,79,105,1.0)
$font_color = rgba(76,79,105,1.0)
$placeholder_color = rgba(76,79,105,0.6)
$check_color = rgba(30,102,245,1.0)    # Catppuccin Latte Blue
$fail_color = rgba(210,15,57,1.0)      # Catppuccin Latte Red
