# Catppuccin Latte — Sway theme tokens

titlebar                  borderless
titlebar button           off

client.focused           #4c4f69 #eff1f5 #4c4f69 #dce0e8 #4c4f69
client.unfocused         #9ca0b0 #e6e9ef #9ca0b0 #dce0e8 #9ca0b0
client.focused_inactive  #9ca0b0 #e6e9ef #9ca0b0 #dce0e8 #9ca0b0
client.urgent            #d20f39 #e6e9ef #d20f39 #dce0e8 #d20f39
