# Use defaults Omarchy defaults
source = ~/.dots/default/hypr/autostart.conf
source = ~/.dots/default/hypr/bindings/media.conf
source = ~/.dots/default/hypr/bindings/tiling.conf
source = ~/.dots/default/hypr/bindings/utilities.conf
source = ~/.dots/default/hypr/envs.conf
source = ~/.dots/default/hypr/looknfeel.conf
source = ~/.dots/default/hypr/input.conf
source = ~/.dots/default/hypr/windows.conf
source = ~/.dots/default/hypr/monitors.conf
source = ~/.dots/current/theme/hyprland.conf


