#!/usr/bin/env bash
# Desktop profile (shared base) — compositor-agnostic.
#
# Installs the common Wayland stack that every supported compositor
# (Sway, Hyprland, ...) relies on. The chosen compositor itself is
# installed by one of the install/compositor-*.sh adapters, selected
# by the DOTS_COMPOSITOR environment variable (or the prompt below).
#
# Everything in this script is compositor-neutral by design:
#   * no sway/hyprctl-specific packages beyond the universal Wayland
#     tools (waybar, mako, polkit);
#   * no per-compositor shell autostart logic — that lives in the
#     adapter and the bash_profile generated by it;
#   * no wallpaper daemon, lock screen, or idle manager — each
#     compositor adapter provides its own.
#
# Adding or removing tools here should never require touching the
# compositor adapters. Conversely, changing compositor behavior should
# not require touching this file.

set -euo pipefail

DOTS="${DOTS:-$HOME/.dots}"
source "$DOTS/lib/helpers.sh"

# ---------------------------------------------------------------------------
# Compositor selection (env var > interactive prompt)
# ---------------------------------------------------------------------------
if [[ -z "${DOTS_COMPOSITOR:-}" ]]; then
    if command -v gum &>/dev/null; then
        DOTS_COMPOSITOR=$(gum choose sway hyprland --header "Select compositor adapter")
    else
        PS3="Select compositor adapter [sway/hyprland]: "
        select c in sway hyprland; do
            DOTS_COMPOSITOR="$c"; break
        done
    fi
fi
case "$DOTS_COMPOSITOR" in
    sway|hyprland) export DOTS_COMPOSITOR ;;
    *) echo "Unknown compositor: $DOTS_COMPOSITOR (expected sway or hyprland)"; exit 1 ;;
esac
echo "==> Compositor adapter: $DOTS_COMPOSITOR"

# ---------------------------------------------------------------------------
# Shared Wayland + desktop base
# ---------------------------------------------------------------------------

# Wayland panels, notifications, auth agent, clipboard
paru -S --noconfirm --needed \
    waybar mako polkit-gnome \
    wl-clipboard wl-clip-persist cliphist \
    grim slurp swappy \
    libnotify imagemagick jq

# PipeWire audio + media keys
paru -S --noconfirm --needed \
    pipewire wireplumber playerctl

# TUIs referenced by shared keybindings / scripts
paru -S --noconfirm --needed \
    alacritty yazi btop \
    impala bluetui wiremix

# Display / brightness / idle daemons shared by both adapters
paru -S --noconfirm --needed \
    brightnessctl wlsunset kanshi

# Fonts (alacritty uses Fira Code NF; noto for fallback)
paru -S --noconfirm --needed \
    ttf-firacode-nerd noto-fonts noto-fonts-emoji

# Browser referenced by shared keybindings
paru -S --noconfirm --needed google-chrome

# ---------------------------------------------------------------------------
# XDG defaults + TUI .desktop launchers (shared with both adapters)
# ---------------------------------------------------------------------------
source "$DOTS/install/mimetype.sh"

# ---------------------------------------------------------------------------
# yazi as the default file manager
# ---------------------------------------------------------------------------
# Make sure the desktop entry is registered with xdg-open so any app
# (Chrome's "Show in folder", Firefox download manager, etc.) ends up
# opening a FloatingWindow-classed alacritty running yazi. The desktop
# entry itself lives at config/applications/yazi.desktop and is
# symlinked into ~/.local/share/applications/ by the manifest deploy.
if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default yazi.desktop inode/directory >/dev/null 2>&1 || true
    # Refresh the desktop + mime caches so the new entry is discoverable
    # by apps that consult them directly (Chrome, GTK file-chooser, etc.).
    command -v update-desktop-database >/dev/null \
        && update-desktop-database -q "$HOME/.local/share/applications" 2>/dev/null || true
    command -v update-mime-database >/dev/null \
        && update-mime-database "$HOME/.local/share/mime" 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# Patched mako (per-notification position via x-dots-position hint)
# ---------------------------------------------------------------------------
# If ~/.local/src/mako is present (cloned with the position-hint branch
# applied), rebuild and install the patched binary into ~/.local/bin so
# 'mako' resolves to it. The autostart calls /home/usrtmp/.local/bin/mako
# by full path, so this is the source of truth for what mako runs.
if [[ -d "$HOME/.local/src/mako" ]] && command -v meson >/dev/null 2>&1; then
    echo "==> Rebuilding patched mako from ~/.local/src/mako"
    (cd "$HOME/.local/src/mako" && ninja -C build >/dev/null 2>&1) \
        || meson setup build >/dev/null 2>&1 && ninja -C build >/dev/null 2>&1
    mkdir -p "$HOME/.local/bin"
    install -m 0755 "$HOME/.local/src/mako/build/mako" "$HOME/.local/bin/mako"
fi

# ---------------------------------------------------------------------------
# Waybar workspace module: pick the right one for the active compositor
# ---------------------------------------------------------------------------
"$DOTS/bin/script-apply-waybar-compositor" || true

# ---------------------------------------------------------------------------
# Compositor adapter (sway or hyprland)
# ---------------------------------------------------------------------------
case "$DOTS_COMPOSITOR" in
    sway)      "$DOTS/install/compositor-sway.sh" ;;
    hyprland)  "$DOTS/install/compositor-hyprland.sh" ;;
esac

# ---------------------------------------------------------------------------
# TTY autologin (shared base) — the adapter decides what to launch
# ---------------------------------------------------------------------------
OVERRIDE_DIR=/etc/systemd/system/getty@tty1.service.d
sudo mkdir -p "$OVERRIDE_DIR"
sudo tee "$OVERRIDE_DIR/autologin.conf" >/dev/null <<EOF
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin $USER --noclear %I \$TERM
EOF
sudo systemctl daemon-reload

# ~/.bash_profile sources the adapter-provided session entrypoint, falling
# back to the env var if no adapter file is present.
cat > ~/.bash_profile <<EOF
# Auto-start the selected compositor on tty1 (no display manager)
if [[ -z "\$DISPLAY" && -z "\$WAYLAND_DISPLAY" && "\$XDG_VTNR" -eq 1 ]]; then
    if [[ -x "\$HOME/.dots/bin/dots-session" ]]; then
        exec \$HOME/.dots/bin/dots-session
    elif [[ -n "\${DOTS_COMPOSITOR:-}" ]]; then
        case "\$DOTS_COMPOSITOR" in
            sway)     exec sway ;;
            hyprland) exec Hyprland ;;
        esac
    else
        exec sway
    fi
fi
EOF

echo "Desktop base installed. Compositor adapter: $DOTS_COMPOSITOR."
echo "Reboot to auto-login into $DOTS_COMPOSITOR on tty1."