# Close window
bind = SUPER, W, killactive,

# Control tiling
# bind = SUPER, J, togglesplit, # dwindle
bind = SUPER, F, exec, hyprctl dispatch togglefloating && hyprctl dispatch centerwindow activewindow

# Toggle master on left/right side
bind = SUPER, O, layoutmsg, orientationnext

# Move focus with mainMod + arrow keys
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = SUPER, code:10, workspace, 1
bind = SUPER, code:11, workspace, 2
bind = SUPER, code:12, workspace, 3
bind = SUPER, code:13, workspace, 4
bind = SUPER, code:14, workspace, 5
bind = SUPER, code:15, workspace, 6
bind = SUPER, code:16, workspace, 7
bind = SUPER, code:17, workspace, 8
bind = SUPER, code:18, workspace, 9
bind = SUPER, code:19, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = SUPER SHIFT, code:10, movetoworkspacesilent, 1
bind = SUPER SHIFT, code:11, movetoworkspacesilent, 2
bind = SUPER SHIFT, code:12, movetoworkspacesilent, 3
bind = SUPER SHIFT, code:13, movetoworkspacesilent, 4
bind = SUPER SHIFT, code:14, movetoworkspacesilent, 5
bind = SUPER SHIFT, code:15, movetoworkspacesilent, 6
bind = SUPER SHIFT, code:16, movetoworkspacesilent, 7
bind = SUPER SHIFT, code:17, movetoworkspacesilent, 8
bind = SUPER SHIFT, code:18, movetoworkspacesilent, 9
bind = SUPER SHIFT, code:19, movetoworkspacesilent, 10

# Swap active window with the one next to it with mainMod + SHIFT + arrow keys
bind = SUPER SHIFT, left, swapwindow, l
bind = SUPER SHIFT, right, swapwindow, r
bind = SUPER SHIFT, up, swapwindow, u
bind = SUPER SHIFT, down, swapwindow, d
bind = SUPER SHIFT, h, swapwindow, l
bind = SUPER SHIFT, l, swapwindow, r
bind = SUPER SHIFT, k, swapwindow, u
bind = SUPER SHIFT, j, swapwindow, d

# Enter move/resize mode
bind = SUPER, R, submap, MOVE_RESIZE

submap = MOVE_RESIZE
# Move/resize keybindings inside the mode
binde = , F, fullscreen
binde = , H, moveactive, -20 0
binde = , L, moveactive, 20 0
binde = , K, moveactive, 0 -20
binde = , J, moveactive, 0 20

binde = ALT, h, resizeactive, -20 0
binde = ALT, l, resizeactive, 20 0
binde = ALT, k, resizeactive, 0 -20
binde = ALT, j, resizeactive, 0 20
binde = SHIFT, h, moveactive, -20 0
binde = SHIFT, h, resizeactive, 20 0
binde = SHIFT, l, moveactive, 20 0
binde = SHIFT, l, resizeactive, -20 0
binde = SHIFT, k, moveactive, 0 -20
binde = SHIFT, k, resizeactive, 0 20
binde = SHIFT, j, moveactive, 0 20
binde = SHIFT, j, resizeactive, 0 -20

# Exit the mode
bind = , escape, submap, reset

submap = reset

# Scroll through existing workspaces with mainMod + scroll
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, TAB, workspace, e+1
bind = SUPER SHIFT, TAB, workspace, e-1
