# Application bindings
$terminal = alacritty
$browser = firefox
$webapp = $browser -no-remote --profile "/home/usrtmp/.mozilla/firefox/8eljf7n1.appmode/"
$podman_as_docker = DOCKER_HOST=unix:///run/user/$(id -u)/podman/podman.sock
# Launching
bind = SUPER, B, exec, $browser
bind = SUPER, return, exec, $terminal

bind = SUPER, E, exec, alacritty --class="FloatingWindow" -e yazi
bind = SUPER, T, exec, alacritty --class="FloatingWindow" -e btop
bind = SUPER, Z, exec, alacritty --class="FloatingWindow" -e impala
bind = SUPER, X, exec, alacritty --class="FloatingWindow" -e wiremix
bind = SUPER, C, exec, alacritty --class="FloatingWindow" -e bluetui
bind = SUPER, grave, exec, alacritty --class="FloatingWindow" -e ~/.dots/bin/script-manage
bind = SUPER, D, exec, bash -c  '$podman_as_docker $terminal --class=FloatingWindow -e lazydocker'

bind = SUPER, M, exec, sh -c '$webapp "https://music.youtube.com/"'
bind = SUPER, A, exec, sh -c '$webapp "https://chatgpt.com"'
bind = SUPER SHIFT, A, exec, sh -c '$webapp "https://gemini.google.com/u/0/app"'

# Aesthetics
bind = SUPER SHIFT, SPACE, exec, pkill -SIGUSR1 waybar
bind = SUPER, SPACE, exec, fuzzel --lines 5

# Notifications
bind = SUPER, comma, exec, makoctl dismiss
bind = SUPER SHIFT, comma, exec, makoctl dismiss --all
bind = SUPER CTRL, comma, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

# Power menu controls lock, suspend, relaunch, restart, shutdown
bind = SUPER, ESCAPE, exec, ~/.dots/bin/script-power
bind = SUPER, P, exec, ~/.dots/bin/script-monitor-display

# Toggle idling
bind = SUPER CTRL, I, exec, ~/.dots/bin/script-toggle-idle
bind = SUPER, I, exec, ~/.dots/bin/script-info

# Clipboard history
bind = SUPER, V, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy 

# Screenshots
bind = , PRINT, exec, hyprshot -m region
bind = SHIFT, PRINT, exec, hyprshot -m window
bind = CTRL, PRINT, exec, hyprshot -m output
bind = SUPER, S, exec, hyprshot -m region
bind = SUPER SHIFT, S, exec, hyprshot -m window
bind = SUPER CTRL, S, exec, hyprshot -m output

# Color picker
bind = SUPER, PRINT, exec, hyprpicker -a
bind = SUPER ALT, S, exec, hyprpicker -a

bind = SUPER, N, exec, ~/.dots/bin/script-toggle-sunset

